const express = require('express');
const { body, validationResult } = require('express-validator');
const { initiateSTKPush, queryTransactionStatus } = require('../config/mpesa');
const Token = require('../models/Token');
const logger = require('../config/logger');

const router = express.Router();

/**
 * POST /api/payments/initiate
 * Initiates M-Pesa payment for 24-hour access token
 * Body: { phoneNumber: string, email?: string, firstName?: string, lastName?: string }
 */
router.post(
  '/initiate',
  [
    body('phoneNumber')
      .trim()
      .matches(/^(\+?254|0)[1-9]\d{8}$/)
      .withMessage('Invalid Kenyan phone number format'),
    body('email')
      .isEmail()
      .withMessage('Invalid email address'),
    body('amount')
      .optional()
      .isFloat({ gt: 0 })
      .withMessage('Amount must be a positive number')
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
      }

      const { phoneNumber, email, firstName, lastName, amount: amt } = req.body;
      // allow dynamic amount from request or fallback to environment/default
      const amount = amt ? parseFloat(amt) : (parseFloat(process.env.PAYMENT_AMOUNT) || 100);

      // Generate reference ID (order ID)
      const referenceId = `TOKEN_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      const tokenValue = `tok_${Math.random().toString(36).substr(2, 18)}`;

      // Initiate M-Pesa STK push
      const amountToCharge = amount;
      const orderId = referenceId;

      let result = await initiateSTKPush(phoneNumber, amountToCharge, orderId);

      // if the real API was used and we got a network/timeout error,
      // do not fall back to the mock in production.
      const usingMock =
        process.env.USE_MOCK_MPESA === '1' ||
        process.env.USE_MOCK_MPESA === 'true' ||
        process.env.NODE_ENV !== 'production';

      if (!result.success && process.env.NODE_ENV !== 'production') {
        // some kind of failure (network, configuration, validation on Safaricom side)
        // automatically try the mock implementation during development.
        logger.warn('M-Pesa initiation failed; falling back to mock', {
          phoneNumber,
          error: result.error
        });
        const { initiateSTKPush: mockPush } = require('../config/mpesa-mock');
        result = await mockPush(phoneNumber, amountToCharge, orderId);
      }

      if (!result.success) {
        logger.error('M-Pesa STK push initiation failed', { error: result.error, phoneNumber });
        return res.status(400).json({
          success: false,
          message: 'Failed to initiate payment',
          error: result.error
        });
      }

      // Store pending token in database (store checkoutRequestId as orderTrackingId)
      const tokenData = new Token({
        token: tokenValue,
        referenceId,
        orderTrackingId: result.checkoutRequestId || result.requestId || null,
        phoneNumber,
        email,
        amount: amountToCharge,
        paymentStatus: 'pending',
        paymentGateway: 'mpesa',
        expiresAt: new Date(Date.now() + 30 * 60 * 1000) // 30 minutes for payment completion
      });

      await tokenData.save();

      logger.info('Payment initiated successfully', { referenceId, checkoutRequestId: result.checkoutRequestId });

      res.status(200).json({
        success: true,
        message: 'Payment initiated successfully',
        checkoutRequestId: result.checkoutRequestId,
        amount: amountToCharge,
        currency: 'KES'
      });
    } catch (error) {
      logger.error('Payment initiation error', { error: error.message });
      res.status(500).json({
        success: false,
        message: 'Internal server error',
        error: process.env.NODE_ENV === 'development' ? error.message : undefined
      });
    }
  }
);

/**
 * POST /api/payments/query
 * Query the status of a payment transaction
 * Body: { orderTrackingId: string }
 */
router.post(
  '/query',
  [
    body('orderTrackingId')
      .trim()
      .notEmpty()
      .withMessage('Order tracking ID is required')
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
      }

      const { orderTrackingId } = req.body;

      let result;
      const usingMock =
        process.env.USE_MOCK_MPESA === '1' ||
        process.env.USE_MOCK_MPESA === 'true';

      // if the id was generated by our fallback/mock code, always query the mock
      const isMockId = orderTrackingId && orderTrackingId.startsWith('MOCK_');
      if (usingMock || isMockId) {
        const { queryTransactionStatus: mockQuery } = require('../config/mpesa-mock');
        result = await mockQuery(orderTrackingId);
      } else {
        result = await queryTransactionStatus(orderTrackingId);
        // any failure on the real query should also trigger a mock lookup so
        // that pending/mock identifiers are handled correctly
        if (!result.success && !usingMock) {
          logger.warn('Real M-Pesa query failed; falling back to mock', {
            orderTrackingId,
            error: result.error
          });
          const { queryTransactionStatus: mockQuery } = require('../config/mpesa-mock');
          result = await mockQuery(orderTrackingId);
        }
      }

      // Determine payment status based on response codes
      let paymentStatus = 'PENDING';
      
      if (result.success && result.resultCode === '0') {
        paymentStatus = 'COMPLETED';
        
        // Update token status in database
        const token = await Token.findOne({ orderTrackingId });
        if (token) {
          token.paymentStatus = 'completed';
          token.expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours
          await token.save();
          logger.info('Payment completed', { orderTrackingId, tokenId: token._id });
        }
      } else if (result.resultCode !== '0' && result.resultCode) {
        paymentStatus = 'FAILED';
      }

      res.status(200).json({
        success: paymentStatus === 'COMPLETED',
        status: paymentStatus,
        message: result.message || 'Payment status retrieved',
        resultDesc: result.resultDesc
      });
    } catch (error) {
      logger.error('Payment query error', { error: error.message });
      res.status(500).json({
        success: false,
        status: 'ERROR',
        message: 'Internal server error',
        error: process.env.NODE_ENV === 'development' ? error.message : undefined
      });
    }
  }
);

/**
 * POST /api/payments/callback
 * M-Pesa callback endpoint (alias for /api/payment/mpesa-callback)
 * This is called by M-Pesa servers after payment
 */
router.post('/callback', async (req, res) => {
  try {
    const { Body } = req.body;
    if (!Body || !Body.stkCallback) {
      logger.warn('Invalid M-Pesa callback structure', { body: req.body });
      return res.status(200).json({ success: false });
    }

    const stkCallback = Body.stkCallback;
    logger.info('M-Pesa Callback (payments alias)', {
      checkoutId: stkCallback.CheckoutRequestID,
      resultCode: stkCallback.ResultCode
    });

    // Check if payment was successful
    if (stkCallback.ResultCode !== 0) {
      logger.warn(`Payment failed with code: ${stkCallback.ResultCode}`);
      return res.status(200).json({ success: false });
    }

    // Extract payment metadata
    const callbackMetadata = stkCallback.CallbackMetadata?.Item || [];
    const paymentData = {};

    callbackMetadata.forEach(item => {
      if (item.Name === 'Amount') {paymentData.amount = item.Value;}
      if (item.Name === 'MpesaReceiptNumber') {paymentData.mpesaReceiptNumber = item.Value;}
      if (item.Name === 'TransactionDate') {paymentData.transactionDate = item.Value;}
      if (item.Name === 'PhoneNumber') {paymentData.phoneNumber = item.Value;}
    });

    const checkoutRequestId = stkCallback.CheckoutRequestID;

    // Update token in database
    const token = await Token.findOneAndUpdate(
      { orderTrackingId: checkoutRequestId },
      {
        phoneNumber: paymentData.phoneNumber,
        amount: paymentData.amount,
        mpesaReceiptNumber: paymentData.mpesaReceiptNumber,
        paymentStatus: 'completed',
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
        paymentGateway: 'mpesa'
      },
      { new: true }
    );

    if (token) {
      logger.info('Payment completed via callback', { tokenId: token._id });
    }

    res.status(200).json({ success: true });
  } catch (error) {
    logger.error('Callback processing error', { error: error.message });
    res.status(200).json({ success: false });
  }
});

/**
 * GET /api/payments/verify/:phoneNumber
 * Verify if user has valid access token
 */
router.get('/verify/:phoneNumber', async (req, res) => {
  try {
    const { phoneNumber } = req.params;

    const token = await Token.findOne({
      phoneNumber: phoneNumber,
      paymentStatus: 'completed',
      expiresAt: { $gt: new Date() }
    });

    if (!token) {
      logger.info('Token verification failed', { phoneNumber });
      return res.status(404).json({
        hasAccess: false,
        message: 'No valid access token found'
      });
    }

    logger.info('Token verified', { tokenId: token._id, phoneNumber });
    res.status(200).json({
      hasAccess: true,
      token: token._id,
      expiresAt: token.expiresAt,
      remainingTime: `${Math.round((token.expiresAt - new Date()) / 1000 / 60)  } minutes`,
      message: 'Valid access token'
    });
  } catch (error) {
    logger.error('Token verification error', { error: error.message });
    res.status(500).json({
      hasAccess: false,
      message: 'Internal server error',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

module.exports = router;
